global_defs {
	notification_email {
		acassen@firewall.loc
		failover@firewall.loc
		sysadmin@firewall.loc
	}
	notification_email_from Alexandre.Cassen@firewall.loc
	smtp_server [ip地址]
	smtp_connect_timeout 30
	router_id LVS_DEVELBACK
}

#检测脚本
vrrp_script chk_http_port {
	script "/usr/local/src/nginx_check.sh"	#此处为检测脚本地址
	interval 2 #检测间隔
	weight 2
}

vrrp_instance VI_1 {
	state [身份]	#此处为服务器身份，主MASTER，从BACKUP
	interface ens160	#网卡名称
	virtual_router_id 51	#虚拟路由id，主从一致
	priority 100	#优先级,越大越优先
	advert_int 1
	authentication {
		auth_type PASS
		auth_pass 1111
	}
	virtual_ipaddress {
		192.168.40.100	#虚拟地址
	}
	track_script {
		chk_http_port
	}
}